# Generated by Django 2.0 on 2020-03-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbageSysApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarbagePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(blank=True, max_length=1000)),
                ('Latitude', models.IntegerField(blank=True, default=0)),
                ('Longitude', models.IntegerField(blank=True, default=0)),
                ('UID', models.CharField(blank=True, max_length=1000)),
                ('RegisteredBy', models.CharField(blank=True, max_length=1000)),
                ('FilledPercent', models.IntegerField(blank=True, default=0)),
                ('StatusChoices', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], max_length=25)),
            ],
        ),
    ]
